# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 822138cadfb8d32436a87a8842e4a63e343e0fccba92330ddb11f3ab29e9e5ef0233042a2003440890b6683bd54b9524e8599df7c2d225fb018c2a6d529fc50a

test:
  secret_key_base: 5bf310eff609e072898fb3a49629eb9a1dada397d62995206ca9924ff033728d4721229e4dc683ea8e650d1219ad6f496c0be036dca31e07586e5e733c488bcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
